# fly.toml app configuration file generated for delicate-lake-3230 on 2023-09-14T18:54:58-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "delicate-lake-3230"
primary_region = "qro"

[build]

[http_service]
  internal_port = 8081
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[env]
  PORT = 8081
  REGION = "QRO"